/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    AppNavbar: typeof import('./src/components/AppNavbar.vue')['default']
    Container: typeof import('./src/components/Container.vue')['default']
    Home: typeof import('./src/components/pages/Home.vue')['default']
    IFaMoon: typeof import('~icons/fa-regular/moon')['default']
    IFaSun: typeof import('~icons/fa-regular/sun')['default']
    Logo: typeof import('./src/components/Logo.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Slide: typeof import('./src/components/Slide.vue')['default']
    Stats: typeof import('./src/components/Stats.vue')['default']
  }
}
